var numone=20;
var numtwo=30;
var numthree=numone+numtwo;
var numsubract=numone-numtwo;
var nummulti=numone*numtwo;
var numdiv=numone/numtwo;
var nummudulo=numone%numtwo;
console.log(numthree);
console.log(numsubract);
console.log(nummulti);
console.log(numdiv);
console.log(nummudulo);
console.log(numthree--);console.log(--numthree);
console.log(numthree++);
console.log(++numthree);
console.log(20<30);
console.log(20<=20);
console.log(30>30);
console.log(30>=30);
console.log(30!=40);
console.log(2==2);
console.log(2==="2");
